"""Generate a standalone TypeScript WebGPU driver for a ShaderArtifact."""

from __future__ import annotations

import json

from ..schemas.artifact import ShaderArtifact


def generate_typescript_driver(artifact: ShaderArtifact) -> str:
    source = json.dumps(artifact.wgsl_code)
    entries = json.dumps(artifact.bind_group_layout_entries())
    x, y, z = artifact.dispatch_size
    return f"""// Generated by Shader Alchemist. Do not edit generated files.
const shaderCode = {source};
const bindGroupLayoutEntries = {entries};
const dispatchSize = [{x}, {y}, {z}] as const;

export async function createPipeline(device: GPUDevice): Promise<GPUComputePipeline> {{
  const module = device.createShaderModule({{ code: shaderCode }});
  return device.createComputePipeline({{
    layout: device.createPipelineLayout({{
      bindGroupLayouts: [device.createBindGroupLayout({{ entries: bindGroupLayoutEntries }})],
    }}),
    compute: {{ module, entryPoint: {json.dumps(artifact.entry_point)} }},
  }});
}}

export function dispatch(pass: GPUComputePassEncoder): void {{
  pass.dispatchWorkgroups(...dispatchSize);
}}
"""